"""empty message

Revision ID: 8ec737ee1079
Revises: 16f33fa6b672
Create Date: 2022-05-27 09:06:34.069651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec737ee1079'
down_revision = '16f33fa6b672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('show', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'Shows', ['show'], ['id'])
    op.add_column('Shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.drop_column('Shows', 'name')
    op.add_column('Venue', sa.Column('show', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Shows', ['show'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show')
    op.add_column('Shows', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Shows', 'start_time')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show')
    # ### end Alembic commands ###
