"""empty message

Revision ID: a1e2456ced1c
Revises: 6204e24208ea
Create Date: 2022-05-27 05:08:17.442129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e2456ced1c'
down_revision = '6204e24208ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('venue_search', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genre', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('talent_search', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('search_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'search_description')
    op.drop_column('Venue', 'talent_search')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genre')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'venue_search')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
